name: Playwright Tests

# --- Triggers ---
on:
  push:        # Run tests on every push
    branches: [ "main", "master" ]
  workflow_dispatch:   # Allow manual trigger
  schedule:            # Daily at 9 AM IST (03:30 UTC)
    - cron: "30 3 * * *"

jobs:
  e2e-tests:
    runs-on: ubuntu-latest   # Clean Ubuntu VM

    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # Install Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Install Playwright browsers
      - name: Install browsers (Only Chromium - faster CI)
      #  run: npx playwright install --with-deps -- this will install all browsers
        run: npx playwright install chromium --with-deps

      # Set environment variables from GitHub Secrets
      - name: Set ENV variables
        run: |
          echo "BASE_URL=$BASE_URL" >> $GITHUB_ENV
          echo "USER_EMAIL=$USER_EMAIL" >> $GITHUB_ENV
          echo "USER_PASSWORD=$USER_PASSWORD" >> $GITHUB_ENV
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

      # Run Playwright tests
      - name: Run tests
        run: npx playwright test --reporter=html

      # Generate timestamp
      - name: Generate timestamp
        id: timestamp
        run: echo "ts=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      # Upload HTML report with timestamp
      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: run-report-${{ steps.timestamp.outputs.ts }}
          path: playwright-report/
          retention-days: 15

      # Dummy Slack notification
      - name: Slack Notification (placeholder)
        if: always()
        run: echo "Slack notification goes here."

      # Dummy Jira integration
      - name: Post to Jira (placeholder)
        if: always()
        run: echo "Jira integration goes here."
